spring:
  datasource:
    url: jdbc:h2:mem:graphql
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:admin}
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    com.kurzdigital: DEBUG
    # Request Info
    com.kurzdigital.trawarn.RequestResponseLoggingFilter: DEBUG
    # Debug all keycloak related http communication (huge!!!)
    org.apache.http.wire: INFO
    # Security log
    org.springframework.security: INFO

---
spring:
  profiles: test
  datasource:
    platform: all
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: ca
    password:
  jpa:
    database: h2
    show-sql: true
